final List<Map<String, List>> states = [
  {
    'Abia': [
      'Aba North',
      'Aba South',
      'Arochukwu',
      'Bende',
      'Ikwuano',
      'Isiala Ngwa North',
      'Isiala Ngwa South',
      'Isiukwuato',
      'Obi Ngwa',
      'Ohafia',
      'Osisioma Ngwa',
      'Ugwunagbo',
      'Ukwa East',
      'Ukwa West',
      'Umuahia North',
      'Umuahia South',
      'Umunneochi'
    ]
  },
  {
    'Adamawa': [
      'Demsa',
      'Mayo-Belwa',
      'Fufore',
      'Michika',
      'Ganye',
      'Mubi North',
      'Girei',
      'Mubi South',
      'Gombi',
      'Numan',
      'Guyuk',
      'Shelleng',
      'Hong',
      'Song',
      'Jada',
      'Toungo',
      'Lamurde',
      'Yola North',
      'Madagali',
      'Yola South',
      'Maiha'
    ]
  },
  {
    'Akwa Ibom': [
      'Abak',
      'Eastern Obolo',
      'Eket',
      'Esit Eket',
      'Essien Udim',
      'Etim Ekpo',
      'Etinan',
      'Ibeno',
      'Ibesikpo Asutan',
      'Ibiono Ibom',
      'Ika',
      'Ikono',
      'Ikot Abasi',
      'Ikot Ekpene',
      'Ini',
      'Itu',
      'Mbo',
      'Mkpat Enin',
      'Nsit Atai',
      'Nsit Ibom',
      'Nsit Ubium',
      'Obot Akara',
      'Okobo',
      'Onna',
      'Oron',
      'Oruk Anam',
      'Udung Uko',
      'Ukanafun',
      'Uruan',
      'Urue Offong Oruko',
      'Uyo'
    ]
  },
  {
    'Anambra': [
      'Aguata',
      'Anambra East',
      'Anambra West',
      'Anaocha',
      'Awka North',
      'Awka South',
      'Ayamelum',
      'Dunukofia',
      'Ekwusigo',
      'Idemili North',
      'Idemili South',
      'Ihiala',
      'Njikoka',
      'Nnewi North',
      'Nnewi South',
      'Ogbaru',
      'Onitsha North',
      'Onitsha South',
      'Orumba South',
      'Orumba North',
      'Oyi'
    ]
  },
  {
    'Bauchi': [
      'Alkaleri',
      'Bauchi',
      'Bogoro',
      'Dambam',
      'Darazo',
      'Dass',
      'Gamawa',
      'Ganjuwa',
      'Giade',
      'Itas/gadau',
      'Jamaare',
      'Katagum',
      'Kirfi',
      'Misau',
      'Ningi',
      'Shira',
      'Tafawa Balewa',
      'Toro',
      'Warji',
      'Zaki'
    ]
  },
  {
    'Bayelsa': [
      'Brass',
      'Ekeremor',
      'Kolokuma/opokuma',
      'Nembe',
      'Ogbia',
      'Sagbama',
      'Southern Ijaw',
      'Yenagoa'
    ]
  },
  {
    'Benue': [
      'Ado',
      'Agatu',
      'Apa',
      'Buruku',
      'Gboko',
      'Guma',
      'Gwer East',
      'Gwer West',
      'Katsina-ala',
      'Konshisha',
      'Kwande',
      'Logo',
      'Makurdi',
      'Obi',
      'Ogbadibo',
      'Ohimini',
      'Oju',
      'Okpokwu',
      'Otukpo',
      'Tarka',
      'Ukum',
      'Ushongo',
      'Vandeikya'
    ]
  },
  {
    'Borno': [
      'Abadam',
      'Askira / Uba',
      'Bama',
      'Bayo',
      'Biu',
      'Chibok',
      'Damboa',
      'Dikwa',
      'Gubio',
      'Guzamala',
      'Gwoza',
      'Hawul',
      'Jere',
      'Kaga',
      'Kala Balge',
      'Konduga',
      'Kukawa',
      'Kwaya / Kusar',
      'Mafa',
      'Magumeri',
      'Maiduguri',
      'Marte',
      'Mobbar',
      'Monguno',
      'Ngala',
      'Nganzai',
      'Shani'
    ]
  },
  {
    'CrosRiver': [
      'Abi',
      'Akamkpa',
      'Akpabuyo',
      'Bakassi',
      'Bekwarra',
      'Biase',
      'Boki',
      'Calabar Municipality',
      'Calabar South',
      'Etung',
      'Ikom',
      'Obanliku',
      'Obubra',
      'Obudu',
      'Odukpani',
      'Ogoja'
    ]
  },
  {
    'Delta': [
      'Aniocha North',
      'Aniocha South',
      'Bomadi',
      'Burutu',
      'Ethiope West',
      'Ethiope east',
      'Ika North East',
      'Ika South',
      'Isoko North',
      'Isoko South',
      'Ndokwa East',
      'Ndokwa West',
      'Okpe',
      'Oshimili North',
      'Oshimili South',
      'Patani',
      'Sapele',
      'Udu',
      'Ughelli North',
      'Ughelli South',
      'Ukwuani',
      'Uvwie',
      'Warri North',
      'Warri South',
      'Warri South West'
    ]
  },
  {
    'Ebonyi': [
      'Abakaliki',
      'Afikpo South',
      'Afikpo North',
      'Ebonyi',
      'Ezza North',
      'Ezza South',
      'Ikwo',
      'Ishielu',
      'Ivo',
      'Izzi',
      'Ohaozara',
      'Ohaukwu',
      'Onicha'
    ]
  },
  {
    'Edo': [
      'Akoko Edo',
      'Egor',
      'Esan Central',
      'Esan North East',
      'Esan South East',
      'Esan West',
      'Etsako West',
      'Etsako Central',
      'Etsako East',
      'Igueben',
      'Ikpoba/okha',
      'Oredo',
      'Orhionmwon',
      'Ovia North East',
      'Ovia South West',
      'Owan East',
      'Owan West',
      'Uhunmwode'
    ]
  },
  {
    'Ekiti': [
      'Ado Ekiti',
      'Efon',
      'Ekiti East',
      'Ekiti South West',
      'Ekiti West',
      'Emure',
      'Gbonyin',
      'Ido / Osi',
      'Ijero',
      'Ikere',
      'Ikole',
      'Ilejemeje',
      'Irepodun / Ifelodun',
      'Ise / Orun',
      'Moba',
      'Oye'
    ]
  },
  {
    'Enugu': [
      'Aninri',
      'Awgu',
      'Enugu East',
      'Enugu North',
      'Enugu South',
      'Ezeagu',
      'Igbo Etiti',
      'Igbo Eze North',
      'Igbo Eze South',
      'Isi Uzo',
      'Nkanu East',
      'Nkanu West',
      'Nsukka',
      'Oji-river',
      'Udenu',
      'Udi',
      'Uzo-uwani'
    ]
  },
  {
    'Gombe': [
      'Akko',
      'Balanga',
      'Billiri',
      'Dukku',
      'Funakaye',
      'Gombe',
      'Kaltungo',
      'Kwami',
      'Nafada',
      'Shongom',
      'Yalmaltu / Deba'
    ]
  },
  {
    'Imo': [
      'Aboh Mbaise',
      'Ahiazu Mbaise',
      'Ehime Mbano',
      'Ezinihitte Mbaise',
      'Ideato North',
      'Ideato South',
      'Ihitte/uboma',
      'Ikeduru',
      'Isiala Mbano',
      'Isu',
      'Mbaitoli',
      'Ngor Okpala',
      'Njaba',
      'Nkwerre',
      'Nwangele',
      'Obowo',
      'Oguta',
      'Ohaji/egbema',
      'Okigwe',
      'Onuimo',
      'Orlu',
      'Orsu',
      'Oru East',
      'Oru West',
      'Owerri North',
      'Owerri Urban',
      'Owerri West'
    ]
  },
  {
    'Jigawa': [
      'Auyo',
      'Babura',
      'Birnin Kudu',
      'Birniwa',
      'Buji',
      'Dutse',
      'Gagarawa',
      'Garki',
      'Gumel',
      'Guri',
      'Gwaram',
      'Gwiwa',
      'Hadejia',
      'Jahun',
      'Kafin Hausa',
      'Kaugama',
      'Kazaure',
      'Kirika Samma',
      'Kiyawa',
      'Maigatari',
      'Malam Madori',
      'Miga',
      'Ringim',
      'Roni',
      'Sule-tankarkar',
      'Taura',
      'Yankwashi'
    ]
  },
  {
    'Kaduna': [
      'Birnin Gwari',
      'Chikun',
      'Giwa',
      'Igabi',
      'Ikara',
      'Jaba',
      'Jemaa',
      'Kachia',
      'Kaduna North',
      'Kaduna South',
      'Kagarko',
      'Kajuru',
      'Kaura',
      'Kauru',
      'Kubau',
      'Kudan',
      'Lere',
      'Makarfi',
      'Sabon Gari',
      'Sanga',
      'Soba',
      'Zangon Kataf',
      'Zaria'
    ]
  },
  {
    'Kano': [
      'Ajingi',
      'Albasu',
      'Bagwai',
      'Bebeji',
      'Bichi',
      'Bunkure',
      'Dala',
      'Danbata',
      'Dawaki Kudu',
      'Dawaki Tofa',
      'Doguwa',
      'Fagge',
      'Gabasawa',
      'Garko',
      'Garun Malam',
      'Gaya',
      'Gezawa',
      'Gwale',
      'Gwarzo',
      'Kabo',
      'Kano Municipal',
      'Karaye',
      'Kibiya',
      'Kiru',
      'Kumbotso',
      'Kunchi',
      'Kura',
      'Madobi',
      'Makoda',
      'Minjibir',
      'Nasarawa',
      'Rano',
      'Rimin Gado',
      'Rogo',
      'Shanono',
      'Sumaila',
      'Takai',
      'Tarauni',
      'Tofa',
      'Tsanyawa',
      'Tudun Wada',
      'Ungogo',
      'Warawa',
      'Wudil'
    ]
  },
  {
    'Katsina': [
      'Bakori',
      'Batagarawa',
      'Batsari',
      'Baure',
      'Bindawa',
      'Charanchi',
      'Dan Musa',
      'Dandume',
      'Danja',
      'Daura',
      'Dutsi',
      'Dutsin-ma',
      'Faskari',
      'Funtua',
      'Ingawa',
      'Jibia',
      'Kafur',
      'Kaita',
      'Kankara',
      'Kankia',
      'Katsina',
      'Kurfi',
      'Kusada',
      'Mai adua',
      'Malumfashi',
      'Mani',
      'Mashi',
      'Matazu',
      'Musawa',
      'Rimi',
      'Sabuwa',
      'Safana',
      'Sandamu',
      'Zango'
    ]
  },
  {
    'Kebbi': [
      'Aliero',
      'Arewa',
      'Argungu',
      'Augie',
      'Bagudo',
      'Birnin Kebbi',
      'Bunza',
      'Dandi',
      'Fakai',
      'Gwandu',
      'Jega',
      'Kalgo',
      'Koko/besse',
      'Maiyama',
      'Ngaski',
      'Sakaba',
      'Shanga',
      'Suru',
      'Wasagu/danko',
      'Yauri',
      'Zuru'
    ]
  },
  {
    'Kogi': [
      'Adavi',
      'Ajaokuta',
      'Ankpa',
      'Bassa',
      'Dekina',
      'Ibaji',
      'Idah',
      'Igalamela/odolu',
      'Ijumu',
      'Kabba/bunu',
      'Koton Karfe',
      'Lokoja',
      'Mopa-muro',
      'Ofu',
      'Ogori/magongo',
      'Okehi',
      'Okene',
      'Olamaboro',
      'Omala',
      'Yagba East',
      'Yagba West'
    ]
  },
  {
    'Kwara': [
      'Asa',
      'Baruten',
      'Edu',
      'Ekiti',
      'Ifelodun',
      'Ilorin East',
      'Ilorin South',
      'Ilorin West',
      'Irepodun',
      'Isin',
      'Kaiama',
      'Moro',
      'Offa',
      'Oke - Ero',
      'Oyun',
      'Patigi'
    ]
  },
  {
    'Lagos': [
      'Agege',
      'Ajeromi/ifelodun',
      'Alimosho',
      'Amuwo-odofin',
      'Apapa',
      'Badagry',
      'Epe',
      'Eti-osa',
      'Ibeju/lekki',
      'Ifako-ijaye',
      'Ikeja',
      'Ikorodu',
      'Kosofe',
      'Lagos Island',
      'Lagos Mainland',
      'Mushin',
      'Ojo',
      'Oshodi/isolo',
      'Somolu',
      'Surulere'
    ]
  },
  {
    'Nasarawa': [
      'Akwanga',
      'Awe',
      'Doma',
      'Karu',
      'Keana',
      'Keffi',
      'Kokona',
      'Lafia',
      'Nasarawa',
      'Nasarawa Eggon',
      'Obi',
      'Toto',
      'Wamba'
    ]
  },
  {
    'Niger': [
      'Agaie',
      'Agwara',
      'Bida',
      'Borgu',
      'Bosso',
      'Chanchaga',
      'Edatti',
      'Gbako',
      'Gurara',
      'Katcha',
      'Kontagora',
      'Lapai',
      'Lavun',
      'Magama'
          'Mariga',
      'Mashegu',
      'Mokwa',
      'Munya',
      'Paikoro',
      'Rafi',
      'Rijau',
      'Shiroro',
      'Suleja',
      'Tafa',
      'Wushishi'
    ]
  },
  {
    'Ogun': [
      'Abeokuta North',
      'Abeokuta South',
      'Ado Odo-ota',
      'Ewekoro',
      'Ifo',
      'Ijebu East',
      'Ijebu North',
      'Ijebu North East',
      'Ijebu Ode',
      'Ikenne',
      'Imeko/afon',
      'Ipokia',
      'Obafemi/owode',
      'Odeda',
      'Odogbolu',
      'Ogun Water Side',
      'Remo North',
      'Sagamu',
      'Yewa / Egbado North',
      'Yewa / Egbado South'
    ]
  },
  {
    'Ondo': [
      'Akoko North East',
      'Akoko North West',
      'Akoko South East',
      'Akoko South West',
      'Akure North',
      'Akure South',
      'Ese-odo',
      'Idanre',
      'Ifedore',
      'Ilaje',
      'Ileoluji/okeigbo',
      'Irele',
      'Odigbo',
      'Okitipupa',
      'Ondo East',
      'Ondo West',
      'Ose',
      'Owo',
    ]
  },
  {
    'Osun': [
      'Atakumosa East',
      'Atakumosa West',
      'Ayedaade',
      'Ayedire',
      'Boluwaduro',
      'Boripe',
      'Ede North',
      'Ede South',
      'Egbedore',
      'Ejigbo',
      'Ife Central',
      'Ife East',
      'Ife North',
      'Ife South',
      'Ifedayo',
      'Ifelodun',
      'Ila',
      'Ilesa East',
      'Ilesa West',
      'Irepodun',
      'Irewole',
      'Isokan',
      'Iwo',
      'Obokun',
      'Odo-otin',
      'Ola-oluwa',
      'Olorunda',
      'Oriade',
      'Orolu',
      'Osogbo'
    ]
  },
  {
    'Oyo': [
      'Afijio',
      'Akinyele',
      'Atiba',
      'Atisbo',
      'Egbeda',
      'Ibadan North',
      'Ibadan North East',
      'Ibadan North West',
      'Ibadan South West',
      'Ibadan South-east',
      'Ibarapa Central',
      'Ibarapa East',
      'Ibarapa North',
      'Ido',
      'Irepo',
      'Iseyin',
      'Itesiwaju',
      'Iwajowa',
      'Kajola',
      'Lagelu',
      'Ogbomoso North',
      'Ogbomoso South',
      'Ogo-oluwa',
      'Olorunsogo',
      'Oluyole',
      'Ona-ara',
      'Orelope',
      'Ori Ire',
      'Oyo East',
      'Oyo West',
      'Saki East',
      'Saki West',
      'Surulere'
    ]
  },
  {
    'Plateau': [
      'Barikin Ladi',
      'Bassa',
      'Bokkos',
      'Jos East',
      'Jos North',
      'Jos South',
      'Kanam',
      'Kanke',
      'Langtang North',
      'Langtang South',
      'Mangu',
      'Mikang',
      'Pankshin',
      'Qua\'an Pan',
      'Riyom',
      'Shendam',
      'Wase'
    ]
  },
  {
    'Rivers': [
      'Abua/odual',
      'Ahoada East',
      'Ahoada West',
      'Akuku Toru',
      'Andoni',
      'Asari-toru',
      'Bonny',
      'Degema',
      'Eleme',
      'Emohua',
      'Etche',
      'Gokana',
      'Ikwerre',
      'Khana',
      'Obio/akpor',
      'Ogba/egbema/ndoni',
      'Ogu/bolo',
      'Okrika',
      'Omuma',
      'Opobo/nkoro',
      'Oyigbo',
      'Port Harcourt',
      'Tai'
    ]
  },
  {
    'Sokoto': [
      'Binji',
      'Bodinga',
      'Dange Shuni',
      'Gada',
      'Goronyo',
      'Gudu',
      'Gwadabawa',
      'Illela',
      'Isa',
      'Kebbe',
      'Kware',
      'Rabah',
      'Sabon Birni',
      'Shagari',
      'Silame',
      'Sokoto North',
      'Sokoto South',
      'Tambuwal',
      'Tangaza',
      'Tureta',
      'Wamakko',
      'Wurno',
      'Yabo'
    ]
  },
  {
    'Taraba': [
      'Ardo Kola',
      'Bali',
      'Donga',
      'Gashaka',
      'Gassol',
      'Ibi',
      'Jalingo',
      'Karim Lamido',
      'Kurmi',
      'Lau',
      'Sardauna',
      'Takum',
      'Ussa',
      'Wukari',
      'Yorro',
      'Zing',
    ]
  },
  {
    'Yobe': [
      'Bade',
      'Bursari',
      'Damaturu',
      'Fika',
      'Fune',
      'Geidam',
      'Gujba',
      'Gulani',
      'Jakusko',
      'Karasuwa',
      'Machina',
      'Nangere',
      'Nguru',
      'Potiskum',
      'Tarmuwa',
      'Yunusari',
      'Yusufari'
    ]
  },
  {
    'Zamfara': [
      'Anka',
      'Bakura',
      'Birnin Magaji',
      'Bukkuyum',
      'Bungudu',
      'Gummi',
      'Gusau',
      'Kaura Namoda',
      'Maradun',
      'Maru',
      'Shinkafi',
      'Talata Mafara',
      'Tsafe',
      'Zurmi'
    ]
  }
];
